version: "3.7"

services:

  vsftpd:
    image: panubo/vsftpd
    environment:
      - FTP_USER=ftpuser
      - FTP_PASSWORD=ftppassword
    expose:
      - 21
    volumes:
      - ${MEDIA}:/srv
    network_mode: "host"
