version: "3.7"

services:

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    environment:
      - TZ=${TIMEZONE}
    ports:
      - "9300:9000"
      - "8300:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${STORAGE}/portainer/data:/data