version: "3.7"

services:

  dashy:
    image: lissy93/dashy:latest
    volumes:
      - ${STORAGE}/DashyServer/conf.yml:/app/public/conf.yml
      - ${STORAGE}/DashyServer/item-icons:/app/public/item-icons
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/tcp"
      - "8080:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - ${STORAGE}/PiholeServer/etc-pihole/:/etc/pihole/
      - ${STORAGE}/PiholeServer/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped   
  